--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/minijaham/FeedAndHeal
build-by-default: true
branches:
- master
projects:
  FeedHealCMD:
    path: "https://github.com/minijaham/FeedHealCMD/blob/master/Steak.png"
...
