# Color Codes: use ยง symbol. Visit https://www.digminecraft.com/lists/color_list_pc.php for more information
# Message it sends when successfully executes /feed
feedsuccess: "Successfully Fed!"
# Message it sends when successfully executes /heal
healsuccess: "Successfully Healed!"
# Message that sends to player who executed the commands without permission
nopermission: "You do not have permission to use this command"
# Player join auto feed
auto_feed: true
# Player join auto heal
auto_heal: true
# Touch mode: If you find it troublesome to enter commands, such as a player with a bad name, you can enable this mode,
# click on the player with your set items(id:meta_id)!
touch_mode:
  enable: true
  feed:
    item_id: "348:0"
  heal:
    item_id: "353:0"
  # feed & heal
  fh:
    item_id: "357:0"
# Sound effect when player executes /feed. Default: AnvilUseSound.
feedsound: AnvilUseSound
# Sound effect when player executes /heal. Default: AnvilUseSound.
healsound: AnvilUseSound
# List of sounds: I am officially dumb because I used // and the config didn't even fcking load xD
# AnvilBreakSound
# AnvilFallSound
# AnvilUseSound
# BlazeShootSound
# ClickSound
# DoorBumpSound
# DoorCrashSound
# DoorSound
# EndermanTeleportSound
# FizSound
# GenericSound
# GhastShootSound
# GhastSound
# LaunchSound
# PopSound
# Particle effect. Default: circle.
particle:
  feed:
    type: "circle"
    range: 1
  heal:
    type: "circle"
    range: 1
# List of particle:
# none
# circle
