# Message it sends when successfully executes /feed
feedsuccess: "Successfully Fed!"
# Message it sends when successfully executes /heal
healsuccess: "Successfully Healed!"
# Message that sends to player who executed the commands without permission
nopermission: "You do not have permission to use this command"
# Sound effect when player executes /feed. Default: AnvilUseSound.
feedsound: AnvilUseSound
# Sound effect when player executes /heal. Default: AnvilUseSound.
healsound: AnvilUseSound
# List of sounds: I am officially dumb because I used // and the config didn't even fcking load xD
# AnvilBreakSound
# AnvilFallSound
# AnvilUseSound
# BlazeShootSound
# ClickSOund
# DoorBumpSound
# DoorCrashSound
# DoorSound
# EndermanTeleportSound
# FizSound
# GenericSound
# GhastShootSound
# GhastSound
# LaunchSound
# PopSound
